name: Deploy to AWS

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.91.219.223
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/aqarx-infra
            git pull
            docker-compose -f docker-compose.dev.yml down
            docker-compose -f docker-compose.dev.yml up -d --build
